### ISSUE TITLE
Actividad 1  Alexis Hernández Cruz 

### ISSUE THREAD

**Issue by alex13-loca** [SistemasTecTlaxiaco/actividad-1-mapa-mental-alex13-loca#1]
![alexis 31314](https://user-images.githubusercontent.com/112469592/187811978-5f7f0f84-1ce6-4903-b758-ce2261619f96.png)

Actividad 1
Alexis Hernández Cruz 
1BS

**Comment by YaelTrinidad** [comment]
ACTIVIDAD 1 MAPA MENTAL
DE 20% DE LA ACTIVIDAD OBTUVISTE 14.8% DE ACUERDO A LA RUBRICA

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
